name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deployment step (replace with your deployment logic)
        run: echo "Deploying application..."
        # Add your deployment commands here, e.g. scp, rsync, vercel, netlify-cli, etc.
